apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      # This pulls your private images from GitHub Packages
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.serviceName }}